travis:
  secure:
    BINSTAR_TOKEN: IuvOahqOahwvLI/qaLL5G25zVwUZdnm+II/r9gAkM6x6NPeEWj8Ragjo5RupC3DNeXV5sMq0st3f1liPhWH6RUiCWt2ZtNinrhWYvoZokVNEo9RPU9dfV7MEGgSZSMo+D6rEe5tfBR8P2lOLdL6WcXEbL3u1Z5OMX+BxqIvDRoY4PE4FNO/Lf/cnqPFyHlhb7HxqsmQFUfxuKO0SsKpSSm6hPR4UdxHtS/xO0YvDok71wu0aBr1sO1ry8FD0i9giIEgo+m+ez93pe7O4JcBzIyUus2vmRZE1T35jjPUtrXFAUUHwDMXl0IfQsypDDSE0n0G7IZcjGAa5kjT9rWsaJGfeVBlhmvEpbt9pV6nEMxCI64bBUtq0JxMxqUIVU9gotfwprG92ZRQ8rWxTWyohejwkLgYMTgCLIE1FzGXhbILxT91yoYnnNkqCD28PoPFuXWS9/lNbO+Q43JvgT6mNEjYiEoNmbVrygrcBET3squv/QTgS0G1SlV4WVise+Aypa8ivrraQajLzIEb/dYD57y/nvRY1VabmoUn52tVp+9G7wQM3qQD0/7vxch0puV7WKxXKfJBs1+7XiVqON91HwgLlJ5IiqUvEXcPweghezpmG21cflusQxeb6a96DHVdEUzmrXrCIF85pE62UadhK6vD137p1FDeG6YIErBIDRgQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
